// SPDX-License-Identifier: Apache-2.0
//
// https://github.com/cosmos/ibc/blob/a74555a2613ab957f23c796e1b5bf0b122e6df3b/proto/cli/relayer.proto
// go_package is local so catalyst can vendor the generated client.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: relayer.proto

package relayerapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RelayerApiService_Relay_FullMethodName   = "/ibc.v2.relayer.RelayerApiService/Relay"
	RelayerApiService_Packets_FullMethodName = "/ibc.v2.relayer.RelayerApiService/Packets"
)

// RelayerApiServiceClient is the client API for RelayerApiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RelayerApiServiceClient interface {
	// Relay tracks the packets emitted by a source transaction and submits the
	// transactions required to complete them.
	Relay(ctx context.Context, in *RelayRequest, opts ...grpc.CallOption) (*RelayResponse, error)
	// Packets lists the packets this relayer is aware of, most recent first.
	Packets(ctx context.Context, in *PacketsRequest, opts ...grpc.CallOption) (*PacketsResponse, error)
}

type relayerApiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRelayerApiServiceClient(cc grpc.ClientConnInterface) RelayerApiServiceClient {
	return &relayerApiServiceClient{cc}
}

func (c *relayerApiServiceClient) Relay(ctx context.Context, in *RelayRequest, opts ...grpc.CallOption) (*RelayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RelayResponse)
	err := c.cc.Invoke(ctx, RelayerApiService_Relay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayerApiServiceClient) Packets(ctx context.Context, in *PacketsRequest, opts ...grpc.CallOption) (*PacketsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PacketsResponse)
	err := c.cc.Invoke(ctx, RelayerApiService_Packets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RelayerApiServiceServer is the server API for RelayerApiService service.
// All implementations must embed UnimplementedRelayerApiServiceServer
// for forward compatibility.
type RelayerApiServiceServer interface {
	// Relay tracks the packets emitted by a source transaction and submits the
	// transactions required to complete them.
	Relay(context.Context, *RelayRequest) (*RelayResponse, error)
	// Packets lists the packets this relayer is aware of, most recent first.
	Packets(context.Context, *PacketsRequest) (*PacketsResponse, error)
	mustEmbedUnimplementedRelayerApiServiceServer()
}

// UnimplementedRelayerApiServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRelayerApiServiceServer struct{}

func (UnimplementedRelayerApiServiceServer) Relay(context.Context, *RelayRequest) (*RelayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Relay not implemented")
}
func (UnimplementedRelayerApiServiceServer) Packets(context.Context, *PacketsRequest) (*PacketsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Packets not implemented")
}
func (UnimplementedRelayerApiServiceServer) mustEmbedUnimplementedRelayerApiServiceServer() {}
func (UnimplementedRelayerApiServiceServer) testEmbeddedByValue()                           {}

// UnsafeRelayerApiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RelayerApiServiceServer will
// result in compilation errors.
type UnsafeRelayerApiServiceServer interface {
	mustEmbedUnimplementedRelayerApiServiceServer()
}

func RegisterRelayerApiServiceServer(s grpc.ServiceRegistrar, srv RelayerApiServiceServer) {
	// If the following call pancis, it indicates UnimplementedRelayerApiServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RelayerApiService_ServiceDesc, srv)
}

func _RelayerApiService_Relay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RelayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayerApiServiceServer).Relay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayerApiService_Relay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayerApiServiceServer).Relay(ctx, req.(*RelayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayerApiService_Packets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PacketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayerApiServiceServer).Packets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayerApiService_Packets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayerApiServiceServer).Packets(ctx, req.(*PacketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RelayerApiService_ServiceDesc is the grpc.ServiceDesc for RelayerApiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RelayerApiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ibc.v2.relayer.RelayerApiService",
	HandlerType: (*RelayerApiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Relay",
			Handler:    _RelayerApiService_Relay_Handler,
		},
		{
			MethodName: "Packets",
			Handler:    _RelayerApiService_Packets_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "relayer.proto",
}
