// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: relayerapi/service.proto

package relayerapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransferState int32

const (
	TransferState_TRANSFER_STATE_UNKNOWN  TransferState = 0
	TransferState_TRANSFER_STATE_PENDING  TransferState = 1
	TransferState_TRANSFER_STATE_COMPLETE TransferState = 2
	TransferState_TRANSFER_STATE_FAILED   TransferState = 3
)

// Enum value maps for TransferState.
var (
	TransferState_name = map[int32]string{
		0: "TRANSFER_STATE_UNKNOWN",
		1: "TRANSFER_STATE_PENDING",
		2: "TRANSFER_STATE_COMPLETE",
		3: "TRANSFER_STATE_FAILED",
	}
	TransferState_value = map[string]int32{
		"TRANSFER_STATE_UNKNOWN":  0,
		"TRANSFER_STATE_PENDING":  1,
		"TRANSFER_STATE_COMPLETE": 2,
		"TRANSFER_STATE_FAILED":   3,
	}
)

func (x TransferState) Enum() *TransferState {
	p := new(TransferState)
	*p = x
	return p
}

func (x TransferState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransferState) Descriptor() protoreflect.EnumDescriptor {
	return file_relayerapi_service_proto_enumTypes[0].Descriptor()
}

func (TransferState) Type() protoreflect.EnumType {
	return &file_relayerapi_service_proto_enumTypes[0]
}

func (x TransferState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransferState.Descriptor instead.
func (TransferState) EnumDescriptor() ([]byte, []int) {
	return file_relayerapi_service_proto_rawDescGZIP(), []int{0}
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	ChainId       string                 `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_relayerapi_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relayerapi_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_relayerapi_service_proto_rawDescGZIP(), []int{0}
}

func (x *StatusRequest) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *StatusRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

type TransactionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	ChainId       string                 `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionInfo) Reset() {
	*x = TransactionInfo{}
	mi := &file_relayerapi_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionInfo) ProtoMessage() {}

func (x *TransactionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_relayerapi_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionInfo.ProtoReflect.Descriptor instead.
func (*TransactionInfo) Descriptor() ([]byte, []int) {
	return file_relayerapi_service_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionInfo) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *TransactionInfo) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

type PacketStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	State          TransferState          `protobuf:"varint,1,opt,name=state,proto3,enum=skip.relayer.TransferState" json:"state,omitempty"`
	SequenceNumber uint64                 `protobuf:"varint,2,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	SourceClientId string                 `protobuf:"bytes,3,opt,name=source_client_id,json=sourceClientId,proto3" json:"source_client_id,omitempty"`
	SendTx         *TransactionInfo       `protobuf:"bytes,4,opt,name=send_tx,json=sendTx,proto3" json:"send_tx,omitempty"`
	RecvTx         *TransactionInfo       `protobuf:"bytes,5,opt,name=recv_tx,json=recvTx,proto3" json:"recv_tx,omitempty"`
	AckTx          *TransactionInfo       `protobuf:"bytes,6,opt,name=ack_tx,json=ackTx,proto3" json:"ack_tx,omitempty"`
	TimeoutTx      *TransactionInfo       `protobuf:"bytes,7,opt,name=timeout_tx,json=timeoutTx,proto3" json:"timeout_tx,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PacketStatus) Reset() {
	*x = PacketStatus{}
	mi := &file_relayerapi_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PacketStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketStatus) ProtoMessage() {}

func (x *PacketStatus) ProtoReflect() protoreflect.Message {
	mi := &file_relayerapi_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketStatus.ProtoReflect.Descriptor instead.
func (*PacketStatus) Descriptor() ([]byte, []int) {
	return file_relayerapi_service_proto_rawDescGZIP(), []int{2}
}

func (x *PacketStatus) GetState() TransferState {
	if x != nil {
		return x.State
	}
	return TransferState_TRANSFER_STATE_UNKNOWN
}

func (x *PacketStatus) GetSequenceNumber() uint64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *PacketStatus) GetSourceClientId() string {
	if x != nil {
		return x.SourceClientId
	}
	return ""
}

func (x *PacketStatus) GetSendTx() *TransactionInfo {
	if x != nil {
		return x.SendTx
	}
	return nil
}

func (x *PacketStatus) GetRecvTx() *TransactionInfo {
	if x != nil {
		return x.RecvTx
	}
	return nil
}

func (x *PacketStatus) GetAckTx() *TransactionInfo {
	if x != nil {
		return x.AckTx
	}
	return nil
}

func (x *PacketStatus) GetTimeoutTx() *TransactionInfo {
	if x != nil {
		return x.TimeoutTx
	}
	return nil
}

type StatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PacketStatuses []*PacketStatus        `protobuf:"bytes,1,rep,name=packet_statuses,json=packetStatuses,proto3" json:"packet_statuses,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_relayerapi_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relayerapi_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_relayerapi_service_proto_rawDescGZIP(), []int{3}
}

func (x *StatusResponse) GetPacketStatuses() []*PacketStatus {
	if x != nil {
		return x.PacketStatuses
	}
	return nil
}

type RelayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	ChainId       string                 `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayRequest) Reset() {
	*x = RelayRequest{}
	mi := &file_relayerapi_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayRequest) ProtoMessage() {}

func (x *RelayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relayerapi_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayRequest.ProtoReflect.Descriptor instead.
func (*RelayRequest) Descriptor() ([]byte, []int) {
	return file_relayerapi_service_proto_rawDescGZIP(), []int{4}
}

func (x *RelayRequest) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *RelayRequest) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

type RelayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayResponse) Reset() {
	*x = RelayResponse{}
	mi := &file_relayerapi_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayResponse) ProtoMessage() {}

func (x *RelayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relayerapi_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayResponse.ProtoReflect.Descriptor instead.
func (*RelayResponse) Descriptor() ([]byte, []int) {
	return file_relayerapi_service_proto_rawDescGZIP(), []int{5}
}

var File_relayerapi_service_proto protoreflect.FileDescriptor

const file_relayerapi_service_proto_rawDesc = "" +
	"\n" +
	"\x18relayerapi/service.proto\x12\fskip.relayer\x1a\x1fgoogle/protobuf/timestamp.proto\"C\n" +
	"\rStatusRequest\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\x12\x19\n" +
	"\bchain_id\x18\x02 \x01(\tR\achainId\"E\n" +
	"\x0fTransactionInfo\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\x12\x19\n" +
	"\bchain_id\x18\x02 \x01(\tR\achainId\"\xf8\x02\n" +
	"\fPacketStatus\x121\n" +
	"\x05state\x18\x01 \x01(\x0e2\x1b.skip.relayer.TransferStateR\x05state\x12'\n" +
	"\x0fsequence_number\x18\x02 \x01(\x04R\x0esequenceNumber\x12(\n" +
	"\x10source_client_id\x18\x03 \x01(\tR\x0esourceClientId\x126\n" +
	"\asend_tx\x18\x04 \x01(\v2\x1d.skip.relayer.TransactionInfoR\x06sendTx\x126\n" +
	"\arecv_tx\x18\x05 \x01(\v2\x1d.skip.relayer.TransactionInfoR\x06recvTx\x124\n" +
	"\x06ack_tx\x18\x06 \x01(\v2\x1d.skip.relayer.TransactionInfoR\x05ackTx\x12<\n" +
	"\n" +
	"timeout_tx\x18\a \x01(\v2\x1d.skip.relayer.TransactionInfoR\ttimeoutTx\"U\n" +
	"\x0eStatusResponse\x12C\n" +
	"\x0fpacket_statuses\x18\x01 \x03(\v2\x1a.skip.relayer.PacketStatusR\x0epacketStatuses\"B\n" +
	"\fRelayRequest\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\x12\x19\n" +
	"\bchain_id\x18\x02 \x01(\tR\achainId\"\x0f\n" +
	"\rRelayResponse*\x7f\n" +
	"\rTransferState\x12\x1a\n" +
	"\x16TRANSFER_STATE_UNKNOWN\x10\x00\x12\x1a\n" +
	"\x16TRANSFER_STATE_PENDING\x10\x01\x12\x1b\n" +
	"\x17TRANSFER_STATE_COMPLETE\x10\x02\x12\x19\n" +
	"\x15TRANSFER_STATE_FAILED\x10\x032\x9e\x01\n" +
	"\x11RelayerApiService\x12B\n" +
	"\x05Relay\x12\x1a.skip.relayer.RelayRequest\x1a\x1b.skip.relayer.RelayResponse\"\x00\x12E\n" +
	"\x06Status\x12\x1b.skip.relayer.StatusRequest\x1a\x1c.skip.relayer.StatusResponse\"\x00B4Z2github.com/cosmos/ibc-relayer/proto/gen/relayerapib\x06proto3"

var (
	file_relayerapi_service_proto_rawDescOnce sync.Once
	file_relayerapi_service_proto_rawDescData []byte
)

func file_relayerapi_service_proto_rawDescGZIP() []byte {
	file_relayerapi_service_proto_rawDescOnce.Do(func() {
		file_relayerapi_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_relayerapi_service_proto_rawDesc), len(file_relayerapi_service_proto_rawDesc)))
	})
	return file_relayerapi_service_proto_rawDescData
}

var file_relayerapi_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_relayerapi_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_relayerapi_service_proto_goTypes = []any{
	(TransferState)(0),      // 0: skip.relayer.TransferState
	(*StatusRequest)(nil),   // 1: skip.relayer.StatusRequest
	(*TransactionInfo)(nil), // 2: skip.relayer.TransactionInfo
	(*PacketStatus)(nil),    // 3: skip.relayer.PacketStatus
	(*StatusResponse)(nil),  // 4: skip.relayer.StatusResponse
	(*RelayRequest)(nil),    // 5: skip.relayer.RelayRequest
	(*RelayResponse)(nil),   // 6: skip.relayer.RelayResponse
}
var file_relayerapi_service_proto_depIdxs = []int32{
	0, // 0: skip.relayer.PacketStatus.state:type_name -> skip.relayer.TransferState
	2, // 1: skip.relayer.PacketStatus.send_tx:type_name -> skip.relayer.TransactionInfo
	2, // 2: skip.relayer.PacketStatus.recv_tx:type_name -> skip.relayer.TransactionInfo
	2, // 3: skip.relayer.PacketStatus.ack_tx:type_name -> skip.relayer.TransactionInfo
	2, // 4: skip.relayer.PacketStatus.timeout_tx:type_name -> skip.relayer.TransactionInfo
	3, // 5: skip.relayer.StatusResponse.packet_statuses:type_name -> skip.relayer.PacketStatus
	5, // 6: skip.relayer.RelayerApiService.Relay:input_type -> skip.relayer.RelayRequest
	1, // 7: skip.relayer.RelayerApiService.Status:input_type -> skip.relayer.StatusRequest
	6, // 8: skip.relayer.RelayerApiService.Relay:output_type -> skip.relayer.RelayResponse
	4, // 9: skip.relayer.RelayerApiService.Status:output_type -> skip.relayer.StatusResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_relayerapi_service_proto_init() }
func file_relayerapi_service_proto_init() {
	if File_relayerapi_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_relayerapi_service_proto_rawDesc), len(file_relayerapi_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_relayerapi_service_proto_goTypes,
		DependencyIndexes: file_relayerapi_service_proto_depIdxs,
		EnumInfos:         file_relayerapi_service_proto_enumTypes,
		MessageInfos:      file_relayerapi_service_proto_msgTypes,
	}.Build()
	File_relayerapi_service_proto = out.File
	file_relayerapi_service_proto_goTypes = nil
	file_relayerapi_service_proto_depIdxs = nil
}
