// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: relayerapi/service.proto

package relayerapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RelayerApiService_Relay_FullMethodName  = "/skip.relayer.RelayerApiService/Relay"
	RelayerApiService_Status_FullMethodName = "/skip.relayer.RelayerApiService/Status"
)

// RelayerApiServiceClient is the client API for RelayerApiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RelayerApiServiceClient interface {
	// Relay will track the status of a transfer, and submit the transactions required to complete the transfer via
	// the bridging protocol. The transfer will be updated to PROCESSING until the transfer is completed, or fails.
	Relay(ctx context.Context, in *RelayRequest, opts ...grpc.CallOption) (*RelayResponse, error)
	// Status will return the current status of a transfer. PENDING, PROCESSING, COMPLETED, or FAILED. We assume that
	// the status is PENDING for any transaction that has not been verified by the VerifyRelayPayment operation.
	// The status message will be set if the status is FAILED.
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type relayerApiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRelayerApiServiceClient(cc grpc.ClientConnInterface) RelayerApiServiceClient {
	return &relayerApiServiceClient{cc}
}

func (c *relayerApiServiceClient) Relay(ctx context.Context, in *RelayRequest, opts ...grpc.CallOption) (*RelayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RelayResponse)
	err := c.cc.Invoke(ctx, RelayerApiService_Relay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayerApiServiceClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, RelayerApiService_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RelayerApiServiceServer is the server API for RelayerApiService service.
// All implementations must embed UnimplementedRelayerApiServiceServer
// for forward compatibility.
type RelayerApiServiceServer interface {
	// Relay will track the status of a transfer, and submit the transactions required to complete the transfer via
	// the bridging protocol. The transfer will be updated to PROCESSING until the transfer is completed, or fails.
	Relay(context.Context, *RelayRequest) (*RelayResponse, error)
	// Status will return the current status of a transfer. PENDING, PROCESSING, COMPLETED, or FAILED. We assume that
	// the status is PENDING for any transaction that has not been verified by the VerifyRelayPayment operation.
	// The status message will be set if the status is FAILED.
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	mustEmbedUnimplementedRelayerApiServiceServer()
}

// UnimplementedRelayerApiServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRelayerApiServiceServer struct{}

func (UnimplementedRelayerApiServiceServer) Relay(context.Context, *RelayRequest) (*RelayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Relay not implemented")
}
func (UnimplementedRelayerApiServiceServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedRelayerApiServiceServer) mustEmbedUnimplementedRelayerApiServiceServer() {}
func (UnimplementedRelayerApiServiceServer) testEmbeddedByValue()                           {}

// UnsafeRelayerApiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RelayerApiServiceServer will
// result in compilation errors.
type UnsafeRelayerApiServiceServer interface {
	mustEmbedUnimplementedRelayerApiServiceServer()
}

func RegisterRelayerApiServiceServer(s grpc.ServiceRegistrar, srv RelayerApiServiceServer) {
	// If the following call panics, it indicates UnimplementedRelayerApiServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RelayerApiService_ServiceDesc, srv)
}

func _RelayerApiService_Relay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RelayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayerApiServiceServer).Relay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayerApiService_Relay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayerApiServiceServer).Relay(ctx, req.(*RelayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayerApiService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayerApiServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayerApiService_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayerApiServiceServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RelayerApiService_ServiceDesc is the grpc.ServiceDesc for RelayerApiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RelayerApiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "skip.relayer.RelayerApiService",
	HandlerType: (*RelayerApiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Relay",
			Handler:    _RelayerApiService_Relay_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _RelayerApiService_Status_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "relayerapi/service.proto",
}
