# Reference:
# https://github.com/golangci/golangci-lint/blob/a9caef01ab7f84e049e4818230b34f5d2fe025b0/.golangci.reference.yml
version: "2"

run:
  go: "1.24"
  timeout: 30m
  tests: true

# https://golangci-lint.run/usage/formatters
formatters:
  enable: [gci, gofumpt, goimports, golines]
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/skip-mev/catalyst)
        - blank
      custom-order: true
    golines:
      max-len: 120
  exclusions:
    generated: strict
    paths:
      - .git
      - .github
      - .idea
      - .vscode

# https://golangci-lint.run/usage/linters
linters:
  default: none
  enable:
    - copyloopvar
    - dogsled
    - errcheck
    - goconst
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - revive
    - staticcheck
    - thelper
    - unconvert
    - unparam
    - unused
  settings:
    dogsled:
      max-blank-identifiers: 3
    nolintlint:
      require-explanation: false
      require-specific: false
      allow-unused: true
    revive:
      severity: warning
      rules:
        - name: unused-parameter
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unreachable-code
        - name: redefines-builtin-id
  exclusions:
    generated: strict
    presets:
      - comments
      # - common-false-positives
      # - legacy
      # - std-error-handling
    rules:
      - linters:
          - staticcheck
        path: ^tests/integration/

issues:
  max-issues-per-linter: 50
  max-same-issues: 50
