# Reference:
# https://github.com/golangci/golangci-lint/blob/a9caef01ab7f84e049e4818230b34f5d2fe025b0/.golangci.reference.yml
version: "2"

run:
  go: "1.24"
  timeout: 30m
  tests: true

# https://golangci-lint.run/usage/formatters
formatters:
  enable: [gci, gofumpt, goimports]
  settings:
    gci:
      sections:
          - standard
          - default
          - blank
          - dot
        # todo: ideally should be the following:
        # - standard
        # - default
        # - prefix(github.com/skip-mev/catalyst)
      custom-order: true
  exclusions:
    generated: strict
    paths:
      - ".*\\.pb\\.go$"
      - .git
      - .github
      - .idea
      - .vscode

# https://golangci-lint.run/usage/linters
linters:
  default: none
  enable:
    - copyloopvar
    - dogsled
    - errcheck
    - goconst
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - revive
    - staticcheck
    - thelper
    - unconvert
    - unparam
    - unused
  settings:
    dogsled:
      max-blank-identifiers: 3
    nolintlint:
      require-explanation: false
      require-specific: false
      allow-unused: true
    revive:
      severity: warning
      rules:
        - name: unused-parameter
          disabled: true
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unreachable-code
        - name: redefines-builtin-id
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - revive
        text: avoid meaningless package names
      - linters:
          - gosec
        text: Use of weak random number generator
      - linters:
          - golint
        text: comment on exported var
      - linters:
          - golint
        text: don't use an underscore in package name
      - linters:
          - staticcheck
        text: "ST1003:"
      - linters:
          - staticcheck
        text: "ST1016:"
      - linters:
          - staticcheck
        path: migrations
        text: "SA1019:"
      - linters:
          - staticcheck
        path: ^tests/integration/
      - linters:
          - stylecheck
        text: "ST1001:"

issues:
  max-issues-per-linter: 50
  max-same-issues: 50